[project]
name = "reqlica"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.142.2",
    "httpx>=0.28.1,<1",
]

[project.scripts]
reqlica = "reqlica.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["backend/reqlica"]
